### PR TITLE
Jakob42/feat/linter for forbidden keywords

### PR DESCRIPTION
**Pull request by Jakobus42**
Added an extra file to the functioncheck package which implements a linter for the forbidden keyword check. Please let me know if I can improve on my work:)

Did some testing so the functionality should be fine.

### CODE REVIEW

**Comment by Jakobus42** [comment]
Maybe it would make more sense to not put this in an extra file because it is just 2 functions which would fit well in the function check file, but I wasn't sure because you told me to create an extra file for time implementation

**Review by winstonallo — CHANGES_REQUESTED** [review]
Yea you're right, a separate file is kind of overkill, putting it in the same file would make more sense:) I did not think it would be that little code

**Comment by Jakobus42** [comment]
pushed the changes now^^ just removed the forbiddenkeywords file and moved the content to the functioncheck file

**Review by winstonallo — APPROVED** [review]
👍🏻👍🏻

**Review by winstonallo — APPROVED** [review]

**Pull request merged**
