### PR TITLE
Jakobus42/feat/db

### PR DESCRIPTION
**Pull request by Jakobus42**
- **Database**: Set up the sqlite3 database connection and initialize the required schemas.
- **Data Access Object (DAO)**: Implemented the DAO pattern to handle database interactions with support for CRUD operations.
- **Testing**: Added unit tests to ensure correct functionality of the database connection and DAO operations.

### CODE REVIEW

**Comment by winstonallo** [comment]
I did not know about this, that's so useful for testing 😍 
image

**Comment by winstonallo** [comment]
Love the backup!

**Comment by Jakobus42** [comment]
> Love the backup!

Maybe it also would make sense to store the backup somehow remotely. But that would be a fairly simple change if we decide that we need it.

**Comment by winstonallo** [comment]
> Maybe it also would make sense to store the backup somehow remotely. But that would be a fairly simple change if we decide that we need it.
Yea, as we discussed we can push it on a private repo or sth, but that's not logic that would need to be in the `db` implementation :)

**Review by winstonallo — APPROVED** [review]
LGTM!

**Pull request merged**
